version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'
    env_file: host.env


  runestone:
    image: runestone/server
    restart: always
    #command: tail -F peanutbutter
    volumes:
      - ./:/srv/web2py/applications/runestone
    links:
      - db
    depends_on:
    - "db"
    ports:
      - "80:80"
    env_file: .env
    environment:
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'
      WEB2PY_CONFIG: 'production'
      WEB2PY_MIGRATE: 'Yes'
      DBURL: 'postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone'
      DEV_DBURL: 'postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone'
      TEST_DBURL: 'postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone_test'
      WEB2PY_PASSWORD: 'maison'
      WEB2PY_ADMIN_SECURITY_BYPASS: 'true'

